name: Release VyOS current VM images

on:
  workflow_dispatch:

jobs:
  get_latest_release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      iso_url: ${{ steps.set_iso_url.outputs.iso_url }}
    steps:
      - name: Get version from version.txt
        id: get_version
        run: echo "version=1.3.6" >> $GITHUB_OUTPUT
      - name: Set iso url
        id: set_iso_url
        run: |
          v="1.3.6"
          echo "iso_url: wget https://f.ssh.ax/vyos-1.3.6-amd64.iso"
          echo "iso_url=wget https://f.ssh.ax/vyos-1.3.6-amd64.iso" >> $GITHUB_OUTPUT

  qemu:
    needs: [get_latest_release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cloud_init: ['true', 'false']
        grub_console: ['kvm', 'serial']
    steps:
      - run: pipx install --include-deps ansible
      - run: |
          git clone "https://github.com/higebu/vyos-vm-images" .
          ls .
          ansible-playbook qemu.yml -e cloud_init=${{ matrix.cloud_init}} -e grub_console=${{ matrix.grub_console }} -e vyos_iso_url=${{ needs.get_latest_release.outputs.iso_url }}
      - uses: actions/upload-artifact@v3
        with:
          name: images
          path: build/*.qcow2
          retention-days: 30
          if-no-files-found: error

  lxd:
    needs: [get_latest_release]
    runs-on: ubuntu-latest
    steps:
    
      - run: pipx install --include-deps ansible
      - run: |
          git clone "https://github.com/higebu/vyos-vm-images" .
          ansible-playbook lxd-vm.yml -e vyos_iso_url=${{ needs.get_latest_release.outputs.iso_url }}
      - uses: actions/upload-artifact@v3
        with:
          name: images
          path: build/*.tar.xz
          retention-days: 30
          if-no-files-found: error

  release:
    needs: [get_latest_release, qemu, lxd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create autocommit and tag
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          tagging_message: 1.3.6
          commit_message: BuyOS

      - uses: actions/download-artifact@v3
        id: download
        with:
          name: images

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          artifacts: "*.tar.xz,*.qcow2"
          name: BuyOS 1.3.6
          tag: BuyOS 1.3.6
